name: mcmc_dsfp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - scipy
  - pandas
  - astropy
  - seaborn
  - ipython
  - jupyter
  - pystan
  - arviz
  - corner
  - scikit-learn
  - pip
  - pip:
    - emcee==3.0rc2
    - dynesty
    - theano>=1.0.4
    - pymc3
